# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

# pod update --verbose --no-repo-update

target 'VVCollectProject' do
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'YYCache'
  pod 'BANetManager'
  
end

